---
# Ansible Vault encrypted secrets
# To encrypt: ansible-vault encrypt group_vars/vault.yaml
# To edit: ansible-vault edit group_vars/vault.yaml

vault_ssh_password: "19209746"
vault_gitea_admin_password: "GitAdmin2024!"
vault_gitea_db_password: "GiteaDB2024!"

# Woodpecker CI OAuth2 (from Gitea)
vault_woodpecker_gitea_client: "f072090f-1dea-439e-b4a1-5e52e61b634d"
vault_woodpecker_gitea_secret: "gto_qmbukmbtqumvdfyudyskke6lsjqy5f3hzbs46pfo4ogeuhrvm77a"
