---
apiVersion: v1
kind: Secret
metadata:
  name: woodpecker-secrets
  namespace: woodpecker
type: Opaque
stringData:
  WOODPECKER_AGENT_SECRET: "WOODPECKER_AGENT_SECRET_PLACEHOLDER"
  WOODPECKER_GITEA_CLIENT: "WOODPECKER_GITEA_CLIENT_PLACEHOLDER"
  WOODPECKER_GITEA_SECRET: "WOODPECKER_GITEA_SECRET_PLACEHOLDER"
