---
apiVersion: v1
kind: Secret
metadata:
  name: gitea-secrets
  namespace: gitea
type: Opaque
stringData:
  GITEA__database__PASSWD: "GITEA_DB_PASSWORD_PLACEHOLDER"
  GITEA__security__SECRET_KEY: "GITEA_SECRET_KEY_PLACEHOLDER"
  GITEA__security__INTERNAL_TOKEN: "GITEA_INTERNAL_TOKEN_PLACEHOLDER"
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
  namespace: gitea
type: Opaque
stringData:
  POSTGRES_PASSWORD: "GITEA_DB_PASSWORD_PLACEHOLDER"
