---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - clustertask-git-clone.yaml
  - clustertask-buildah.yaml
  - clustertask-kustomize-deploy.yaml
  - rbac.yaml
  - example-pipeline.yaml
